// Builds deploy/ : a self-contained static site for GitHub Pages / Cloudflare Pages.
//
//   npm run build:deploy        (needs `npm install` and `npm run fetch-assets` first)
//   npm run serve:deploy        (then open http://localhost:8090 to test exactly what will be published)
//
// What it does: copies the page + the few files it needs from node_modules into vendor/, rewrites the import map and
// paths.js to point there, copies the piper-plus voice models, and turns the 118 MB Sudachi binary into gzip parts
// (<= 20 MiB each) plus a manifest, so no single file trips a host's size limit. The Style-BERT-VITS2 panel is left
// disabled in this build (its models are ~500 MB; see README to run it locally).
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "deploy");
const NM = path.join(ROOT, "node_modules");
const PART_BYTES = 20 * 1024 * 1024; // Cloudflare Pages allows 25 MiB per file, GitHub blocks pushes over 100 MB
const SUDACHI_VERSION = "0.1.5";

const log = (...a) => console.log(...a);
const die = (msg) => { console.error(`\nERROR: ${msg}`); process.exit(1); };
const need = (p, hint) => { if (!fs.existsSync(p)) die(`missing ${path.relative(ROOT, p)}. ${hint}`); return p; };

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}
function copyDir(from, to, filter = () => true) {
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, e.name);
    const dst = path.join(to, e.name);
    if (e.isDirectory()) copyDir(src, dst, filter);
    else if (filter(src)) copy(src, dst);
  }
}
const write = (rel, text) => { const p = path.join(OUT, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text); };
const sha256 = (buf) => crypto.createHash("sha256").update(buf).digest("hex");

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// ---- 1. the page itself ---------------------------------------------------------------------------------------------
let html = fs.readFileSync(need(path.join(ROOT, "index.html"), ""), "utf8");
const importMap = `<script type="importmap">
  {
    "imports": {
      "piper-plus": "./vendor/piper-plus/src/index.js",
      "@piper-plus/g2p": "./vendor/g2p/src/index.js",
      "onnxruntime-web": "./vendor/ort/ort.min.mjs",
      "rubberband-wasm": "./vendor/rubberband/index.esm.js"
    }
  }
  </script>`;
const before = html;
html = html.replace(/<script type="importmap">[\s\S]*?<\/script>/, importMap);
if (html === before) die("could not find the import map in index.html");
write("index.html", html);

for (const f of ["app.js", "style.css"]) copy(path.join(ROOT, f), path.join(OUT, f));
for (const f of ["furigana.js", "voicefx.js", "sudachi-glue.js", "sudachi-worker.js"]) copy(path.join(ROOT, "src", f), path.join(OUT, "src", f));
write("src/paths.js", `// GENERATED by scripts/build-deploy.mjs - the hosted build (vendor/ paths, no Style-BERT-VITS2 panel).
export const PATHS = {
  ortDist: "./vendor/ort/",
  piperRustWasm: "./vendor/piper-plus/dist/rust-wasm/piper_plus_wasm.js",
  rubberbandWasm: "./vendor/rubberband/rubberband.wasm",
  sudachiManifest: "models/sudachi/manifest.json",
  sudachiRaw: "models/sudachi/sudachi.wasm",
  sbv2: false,
};
`);
write(".nojekyll", "");
if (fs.existsSync(path.join(ROOT, "models/sudachi/LICENSE-Apache-2.0.txt"))) copy(path.join(ROOT, "models/sudachi/LICENSE-Apache-2.0.txt"), path.join(OUT, "models/sudachi/LICENSE-Apache-2.0.txt"));
copy(path.join(ROOT, "NOTICE.md"), path.join(OUT, "NOTICE.md"));

// ---- 2. vendored libraries (only what the page requests at runtime) ------------------------------------------------------
const piper = need(path.join(NM, "piper-plus"), "Run `npm install`.");
copyDir(path.join(piper, "src"), path.join(OUT, "vendor/piper-plus/src"));
for (const f of ["piper_plus_wasm.js", "piper_plus_wasm_bg.wasm"]) copy(path.join(piper, "dist/rust-wasm", f), path.join(OUT, "vendor/piper-plus/dist/rust-wasm", f));
const g2p = need(path.join(NM, "@piper-plus/g2p"), "Run `npm install`.");
copyDir(path.join(g2p, "src"), path.join(OUT, "vendor/g2p/src"));
copy(path.join(g2p, "data/sv_function_words.json"), path.join(OUT, "vendor/g2p/data/sv_function_words.json"));
const ort = need(path.join(NM, "onnxruntime-web/dist"), "Run `npm install`.");
for (const f of ["ort.min.mjs", "ort-wasm-simd-threaded.jsep.mjs", "ort-wasm-simd-threaded.jsep.wasm"]) copy(path.join(ort, f), path.join(OUT, "vendor/ort", f));
const rb = need(path.join(NM, "rubberband-wasm/dist"), "Run `npm install`.");
copy(path.join(rb, "index.esm.js"), path.join(OUT, "vendor/rubberband/index.esm.js"));
copy(path.join(rb, "rubberband.wasm"), path.join(OUT, "vendor/rubberband/rubberband.wasm"));

// ---- 3. piper-plus voice models ---------------------------------------------------------------------------------------------
for (const name of ["tsukuyomi", "css10", "mera"]) {
  const dir = path.join(ROOT, "models", name);
  const onnx = need(path.join(dir, "model.onnx"), "Run `npm run fetch-assets`.");
  const cfg = need(path.join(dir, "config.json"), "Run `npm run fetch-assets`.");
  copy(onnx, path.join(OUT, "models", name, "model.onnx"));
  copy(cfg, path.join(OUT, "models", name, "config.json"));
  copy(cfg, path.join(OUT, "models", name, "model.onnx.json")); // piper-plus asks for <model>.json first
}

// ---- 4. Sudachi: gzip + split into parts, plus a manifest --------------------------------------------------------------------
const rawPath = need(path.join(ROOT, "models/sudachi/sudachi.wasm"), "Run `npm run fetch-assets`.");
const raw = fs.readFileSync(rawPath);
const gz = zlib.gzipSync(raw, { level: 9 }); // deterministic: same input -> same bytes -> git stores the parts only once
const parts = [];
for (let i = 0, n = 1; i < gz.length; i += PART_BYTES, n++) {
  const slice = gz.subarray(i, i + PART_BYTES);
  const file = `sudachi.wasm.gz.part${n}`;
  write(`models/sudachi/${file}`, slice);
  parts.push({ file, size: slice.length, sha256: sha256(slice) });
}
write("models/sudachi/manifest.json", JSON.stringify({
  name: "sudachi.wasm",
  version: SUDACHI_VERSION,
  source: "npm package sudachi@" + SUDACHI_VERSION + " (github.com/hata6502/sudachi-wasm, Apache-2.0)",
  compression: "gzip",
  rawSize: raw.length,
  rawSha256: sha256(raw),
  parts,
}, null, 2) + "\n");
log(`Sudachi: ${(raw.length / 1048576).toFixed(1)} MiB -> gzip ${(gz.length / 1048576).toFixed(1)} MiB in ${parts.length} parts`);

// ---- 5. report ---------------------------------------------------------------------------------------------------------------
const files = [];
(function walk(d) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); e.isDirectory() ? walk(p) : files.push([p, fs.statSync(p).size]); } })(OUT);
const total = files.reduce((a, [, s]) => a + s, 0);
log(`\ndeploy/: ${files.length} files, ${(total / 1048576).toFixed(0)} MiB total. Largest files:`);
for (const [p, s] of files.sort((a, b) => b[1] - a[1]).slice(0, 10)) log(`  ${(s / 1048576).toFixed(1).padStart(6)} MiB  ${path.relative(OUT, p)}`);
const tooBig = files.filter(([, s]) => s > 100 * 1000 * 1000);
if (tooBig.length) die(`files over GitHub's 100 MB push limit: ${tooBig.map(([p]) => path.relative(OUT, p)).join(", ")}`);
const big = files.filter(([, s]) => s > 25 * 1048576);
if (big.length) log(`\nNote: ${big.length} file(s) exceed Cloudflare Pages' 25 MiB per-file limit (fine on GitHub Pages): ${big.map(([p]) => path.relative(OUT, p)).join(", ")}`);
