// Builds deploy/ : a self-contained static site for GitHub Pages / Cloudflare Pages.
//
//   npm run build:deploy        (needs `npm install` first; runs `npm run files`)
//   npm run serve:deploy        (then open http://localhost:8090 to test exactly what will be published)
//
// What it does: copies the page + yomiage's and wakachi's page code into vendor/, rewrites the import map and paths.js
// to point there, and copies their files folders (made by `npm run files`: parts of at most 20 MB, so the site fits
// GitHub Pages and Cloudflare Pages' 25 MiB per file; the packages download, check and cache them in the browser).
//
//   what                             where
//   voice (yomiage, 65 MB)           yomiage/   parts + engine worker
//   dictionary (wakachi, 42 MB)      wakachi/   parts + Sudachi worker
//
// The Style-BERT-VITS2 panel is left disabled in this build (its models are ~500 MB; see README to run it locally).
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "deploy");
const NM = path.join(ROOT, "node_modules");
const LIMIT_BYTES = 25 * 1024 * 1024; // Cloudflare Pages' per-file limit (the strictest host we target)

const log = (...a) => console.log(...a);
const die = (msg) => { console.error(`\nERROR: ${msg}`); process.exit(1); };
const need = (p, hint) => { if (!fs.existsSync(p)) die(`missing ${path.relative(ROOT, p)}. ${hint}`); return p; };

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}
function copyDir(from, to) {
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, e.name);
    const dst = path.join(to, e.name);
    e.isDirectory() ? copyDir(src, dst) : copy(src, dst);
  }
}
const write = (rel, data) => { const p = path.join(OUT, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, data); };

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// ---- 1. the page itself ---------------------------------------------------------------------------------------------
let html = fs.readFileSync(need(path.join(ROOT, "index.html"), ""), "utf8");
const importMap = `<script type="importmap">
  {
    "imports": {
      "yomiage": "./vendor/yomiage/yomiage.js",
      "wakachi": "./vendor/wakachi/wakachi.js",
      "wakachi/text": "./vendor/wakachi/text.js"
    }
  }
  </script>`;
const before = html;
html = html.replace(/<script type="importmap">[\s\S]*?<\/script>/, importMap);
if (html === before) die("could not find the import map in index.html");
write("index.html", html);

for (const f of ["app.js", "style.css"]) copy(path.join(ROOT, f), path.join(OUT, f));
for (const f of ["voicefx.js", "psola.js"]) copy(path.join(ROOT, "src", f), path.join(OUT, "src", f));
write("src/paths.js", `// GENERATED by scripts/build-deploy.mjs - the hosted build (vendor/ paths, split files, no Style-BERT-VITS2 panel).
export const PATHS = {
  sbv2: false,
};
`);
write(".nojekyll", "");
copy(path.join(ROOT, "NOTICE.md"), path.join(OUT, "NOTICE.md"));
copy(path.join(ROOT, "LICENSE"), path.join(OUT, "LICENSE"));

// ---- 2. the voice: yomiage's page code, and its files (engine worker + voice files in parts) ------------------------
const yomiage = need(path.join(NM, "yomiage/dist/yomiage.js"), "Run `npm install` (and `npm run build` in ../yomiage).");
copy(yomiage, path.join(OUT, "vendor/yomiage/yomiage.js"));
const voiceDir = need(path.join(ROOT, "yomiage/manifest.json"), "Run `npm run yomiage:files`.");
copyDir(path.dirname(voiceDir), path.join(OUT, "yomiage"));

// ---- 3. the dictionary: wakachi's page code, and its files (Sudachi worker + dictionary in parts) ---------------------
for (const f of ["wakachi.js", "text.js"]) copy(need(path.join(NM, "wakachi/dist", f), "Run `npm install` (and `npm run build` in ../wakachi)."), path.join(OUT, "vendor/wakachi", f));
const dictDir = need(path.join(ROOT, "wakachi/manifest.json"), "Run `npm run wakachi:files`.");
copyDir(path.dirname(dictDir), path.join(OUT, "wakachi"));

// ---- 4. report + limits ---------------------------------------------------------------------------------------------------------
const files = [];
(function walk(d) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); e.isDirectory() ? walk(p) : files.push([p, fs.statSync(p).size]); } })(OUT);
const total = files.reduce((a, [, s]) => a + s, 0);
log(`\ndeploy/: ${files.length} files, ${(total / 1048576).toFixed(0)} MiB total. Largest files:`);
for (const [p, s] of [...files].sort((a, b) => b[1] - a[1]).slice(0, 8)) log(`  ${(s / 1048576).toFixed(1).padStart(6)} MiB  ${path.relative(OUT, p)}`);
const over = files.filter(([, s]) => s > LIMIT_BYTES);
if (over.length) die(`files over Cloudflare Pages' 25 MiB limit: ${over.map(([p]) => path.relative(OUT, p)).join(", ")}`);
log("\nOK: no file exceeds 25 MiB (Cloudflare Pages) or 100 MB (GitHub).");
