// Builds deploy/ : a self-contained static site for GitHub Pages / Cloudflare Pages.
//
//   npm run build:deploy        (needs `npm install` and `npm run fetch-assets` first; runs `npm run yomiage:files`)
//   npm run serve:deploy        (then open http://localhost:8090 to test exactly what will be published)
//
// What it does: copies the page + yomiage's page code into vendor/, rewrites the import map and paths.js to point
// there, copies the voice (yomiage/, already in parts of at most 20 MB, made by `yomiage copy-files`), and splits the
// Sudachi binary into parts of at most 20 MiB plus a manifest.json, so the site fits GitHub Pages (100 MB push limit)
// AND Cloudflare Pages (25 MiB per file). The page reassembles the parts in the browser (src/chunks.js), verifies
// their SHA-256 and caches the result in IndexedDB.
//
//   file                         stored as
//   Sudachi binary (118 MiB)     gzip parts                          models/sudachi/
//   voice (yomiage, 65 MB)       its own parts + engine worker       yomiage/
//
// The Style-BERT-VITS2 panel is left disabled in this build (its models are ~500 MB; see README to run it locally).
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "deploy");
const NM = path.join(ROOT, "node_modules");
const PART_BYTES = 20 * 1024 * 1024;
const LIMIT_BYTES = 25 * 1024 * 1024; // Cloudflare Pages' per-file limit (the strictest host we target)
const SUDACHI_VERSION = "0.1.5";

const log = (...a) => console.log(...a);
const die = (msg) => { console.error(`\nERROR: ${msg}`); process.exit(1); };
const need = (p, hint) => { if (!fs.existsSync(p)) die(`missing ${path.relative(ROOT, p)}. ${hint}`); return p; };

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}
function copyDir(from, to) {
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, e.name);
    const dst = path.join(to, e.name);
    e.isDirectory() ? copyDir(src, dst) : copy(src, dst);
  }
}
const write = (rel, data) => { const p = path.join(OUT, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, data); };
const sha256 = (buf) => crypto.createHash("sha256").update(buf).digest("hex");

/**
 * Split `src` into parts of <= PART_BYTES (gzipped first if `gzip`) under deploy/<outRel>/ and write manifest.json.
 * gzip is deterministic, so an unchanged input produces identical parts and git stores them only once.
 */
function chunkFile({ src, outRel, name, version, source, gzip }) {
  const raw = fs.readFileSync(need(src, "Run `npm run fetch-assets` (or `npm install`)."));
  const data = gzip ? zlib.gzipSync(raw, { level: 9 }) : raw;
  const parts = [];
  for (let i = 0, n = 1; i < data.length; i += PART_BYTES, n++) {
    const slice = data.subarray(i, i + PART_BYTES);
    const file = `${name}${gzip ? ".gz" : ""}.part${n}`;
    write(`${outRel}/${file}`, slice);
    parts.push({ file, size: slice.length, sha256: sha256(slice) });
  }
  write(`${outRel}/manifest.json`, JSON.stringify({
    name, version, source, compression: gzip ? "gzip" : "none", rawSize: raw.length, rawSha256: sha256(raw), parts,
  }, null, 2) + "\n");
  const mib = (n) => (n / 1048576).toFixed(1);
  log(`  ${name.padEnd(28)} ${mib(raw.length).padStart(6)} MiB -> ${mib(data.length).padStart(6)} MiB${gzip ? " gzip" : "     "} in ${parts.length} part(s)`);
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// ---- 1. the page itself ---------------------------------------------------------------------------------------------
let html = fs.readFileSync(need(path.join(ROOT, "index.html"), ""), "utf8");
const importMap = `<script type="importmap">
  {
    "imports": {
      "yomiage": "./vendor/yomiage/yomiage.js"
    }
  }
  </script>`;
const before = html;
html = html.replace(/<script type="importmap">[\s\S]*?<\/script>/, importMap);
if (html === before) die("could not find the import map in index.html");
write("index.html", html);

for (const f of ["app.js", "style.css"]) copy(path.join(ROOT, f), path.join(OUT, f));
for (const f of ["chunks.js", "furigana.js", "voicefx.js", "psola.js", "sudachi-glue.js", "sudachi-worker.js"]) copy(path.join(ROOT, "src", f), path.join(OUT, "src", f));
write("src/paths.js", `// GENERATED by scripts/build-deploy.mjs - the hosted build (vendor/ paths, split files, no Style-BERT-VITS2 panel).
export const PATHS = {
  sudachiManifest: "models/sudachi/manifest.json",
  sudachiRaw: "models/sudachi/sudachi.wasm",
  sbv2: false,
};
`);
write(".nojekyll", "");
copy(path.join(ROOT, "NOTICE.md"), path.join(OUT, "NOTICE.md"));
copy(path.join(ROOT, "LICENSE"), path.join(OUT, "LICENSE"));

// ---- 2. the voice: yomiage's page code, and its files (engine worker + voice files in parts) ------------------------
const yomiage = need(path.join(NM, "yomiage/dist/yomiage.js"), "Run `npm install` (and `npm run build` in ../yomiage).");
copy(yomiage, path.join(OUT, "vendor/yomiage/yomiage.js"));
const voiceDir = need(path.join(ROOT, "yomiage/manifest.json"), "Run `npm run yomiage:files`.");
copyDir(path.dirname(voiceDir), path.join(OUT, "yomiage"));

// ---- 3. split files ---------------------------------------------------------------------------------------------------------------
log("Splitting large files:");
chunkFile({
  src: path.join(ROOT, "models/sudachi/sudachi.wasm"), outRel: "models/sudachi", name: "sudachi.wasm", version: SUDACHI_VERSION,
  source: `npm package sudachi@${SUDACHI_VERSION} (github.com/hata6502/sudachi-wasm, Apache-2.0)`, gzip: true,
});
if (fs.existsSync(path.join(ROOT, "models/sudachi/LICENSE-Apache-2.0.txt"))) copy(path.join(ROOT, "models/sudachi/LICENSE-Apache-2.0.txt"), path.join(OUT, "models/sudachi/LICENSE-Apache-2.0.txt"));

// ---- 4. report + limits ---------------------------------------------------------------------------------------------------------
const files = [];
(function walk(d) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); e.isDirectory() ? walk(p) : files.push([p, fs.statSync(p).size]); } })(OUT);
const total = files.reduce((a, [, s]) => a + s, 0);
log(`\ndeploy/: ${files.length} files, ${(total / 1048576).toFixed(0)} MiB total. Largest files:`);
for (const [p, s] of [...files].sort((a, b) => b[1] - a[1]).slice(0, 8)) log(`  ${(s / 1048576).toFixed(1).padStart(6)} MiB  ${path.relative(OUT, p)}`);
const over = files.filter(([, s]) => s > LIMIT_BYTES);
if (over.length) die(`files over Cloudflare Pages' 25 MiB limit: ${over.map(([p]) => path.relative(OUT, p)).join(", ")}`);
log("\nOK: no file exceeds 25 MiB (Cloudflare Pages) or 100 MB (GitHub).");
