// GENERATED by scripts/build-deploy.mjs - the hosted build (vendor/ paths, no Style-BERT-VITS2 panel).
export const PATHS = {
  ortDist: "./vendor/ort/",
  piperRustWasm: "./vendor/piper-plus/dist/rust-wasm/piper_plus_wasm.js",
  rubberbandWasm: "./vendor/rubberband/rubberband.wasm",
  sudachiManifest: "models/sudachi/manifest.json",
  sudachiRaw: "models/sudachi/sudachi.wasm",
  sbv2: false,
};
